!
! FRR Configuration for Group2-Router-P2
! AS20, ISIS IGP, iBGP and eBGP
!
hostname router-P2
password zebra
enable password zebra
!
! Loopback interface with router ID
interface lo
  ip address 100.68.2.3/32
  ipv6 address 2001:db8:2::3/128

!
! Interface eth1 to router-C2
interface eth1
  ip address 100.68.2.19/31
  ipv6 address 2001:db8:2:19::1/64
