!
! FRR Configuration for Group2-Router-C2
! AS20, ISIS IGP, iBGP and eBGP (Route Reflector)
!
hostname router-C2
password zebra
enable password zebra
!
! Loopback interface with router ID
interface lo
  ip address 100.68.2.2/32
  ipv6 address 2001:db8:2::2/128
!
! Interface eth1 to router-B2
interface eth1
  ip address 100.68.2.16/31
  ipv6 address 2001:db8:2:16::1/64
!
! Interface eth2 to router-P2
interface eth2
  ip address 100.68.2.18/31
  ipv6 address 2001:db8:2:18::1/64
!
! Interface eth3 to router-A2
interface eth3
  ip address 100.68.2.20/31
  ipv6 address 2001:db8:2:20::1/64
!
! Interface eth4 to server-SRV2
interface eth4
  ip address 100.68.2.29/30
  ipv6 address 2001:db8:2:29::1/64
!
