!
! FRR Configuration for Group1-Router-A1
! AS10, OSPF IGP, iBGP and eBGP
!
hostname router-A1
password zebra
enable password zebra
!
! Loopback interface with router ID
interface lo
  ip address 100.68.1.4/32
  ipv6 address 2001:db8:1::4/128
!
! Interface eth1 to router-C1
interface eth1
  ip address 100.68.1.21/31
  ipv6 address 2001:db8:1:21::1/64
!
! Interface eth2 to router-Cust1
interface eth2
  ip address 100.68.1.34/31
  ipv6 address 2001:db8:1:34::1/64
!
line vty
!
