!
! FRR Configuration for dist-2 — lớp tuần 2 đã hoàn chỉnh (OSPF + VRRP)
!
hostname dist-2
password zebra
enable password zebra
!
interface eth1.10
  ip address 172.16.10.3/24
  ip ospf passive
  vrrp 10
  vrrp 10 ip 172.16.10.1
  vrrp 10 priority 100
!
interface eth1.20
  ip address 172.16.20.3/24
  ip ospf passive
  vrrp 20
  vrrp 20 ip 172.16.20.1
  vrrp 20 priority 200
!
interface eth2
  ip address 10.0.23.1/30
!
line vty
!
router ospf
  ospf router-id 10.255.0.2
  network 10.0.23.0/30 area 0
  network 172.16.10.0/24 area 0
  network 172.16.20.0/24 area 0
!
