!
hostname r1
password zebra
enable password zebra
!
interface eth1
  ip address 10.1.1.1/24
!
interface eth2
  ip address 10.12.0.1/30
!
line vty
!
router ospf
  router-id 1.1.1.1
  network 10.1.1.0/24 area 1
  network 10.12.0.0/30 area 1
!
