!
! FRR Configuration for Group2-Router-B2
! AS20, ISIS IGP, iBGP and eBGP
!
hostname router-B2
password zebra
enable password zebra
!
! Loopback interface with router ID
interface lo
  ip address 100.68.2.1/32
  ipv6 address 2001:db8:2::1/128
!
! Interface eth1 to router-C2
interface eth1
  ip address 100.68.2.17/31
  ipv6 address 2001:db8:2:17::1/64
!
! Interface eth2 to TR1 (transit router)
interface eth2
  ip address 100.121.1.3/31
  ipv6 address 2001:18:0:11::1/127
!