!
! FRR Configuration for Group1-Router-B1
! AS10, OSPF IGP, iBGP and eBGP
!
hostname router-B1
password zebra
enable password zebra
!
! Loopback interface with router ID
interface lo
  ip address 100.68.1.1/32
  ipv6 address 2001:db8:1::1/128
!
! Interface eth1 to router-C1
interface eth1
  ip address 100.68.1.17/31
  ipv6 address 2001:db8:1:17::1/64
!
! Interface eth2 to TR1 (transit router)
interface eth2
  ip address 100.121.1.1/31
  ipv6 address 2001:18:0:10::1/127
line vty
!
