!
hostname r2
password zebra
enable password zebra
!
interface eth1
  ip address 10.12.0.2/30
!
interface eth2
  ip address 10.23.0.1/30
!
line vty
!
router ospf
  router-id 2.2.2.2
  network 10.12.0.0/30 area 1
  network 10.23.0.0/30 area 0
!
