!
! FRR Configuration for Group1-Router-C1
! AS10, OSPF IGP, iBGP and eBGP (Route Reflector)
!
hostname router-C1
password zebra
enable password zebra
!
! Loopback interface with router ID
interface lo
  ip address 100.68.1.2/32
  ipv6 address 2001:db8:1::2/128
!
! Interface eth1 to router-B1
interface eth1
  ip address 100.68.1.16/31
  ipv6 address 2001:db8:1:16::1/64
!
! Interface eth2 to router-P1
interface eth2
  ip address 100.68.1.18/31
  ipv6 address 2001:db8:1:18::1/64
!
! Interface eth3 to router-A1
interface eth3
  ip address 100.68.1.20/31
  ipv6 address 2001:db8:1:20::1/64
!
! Interface eth4 to server-SRV1
interface eth4
  ip address 100.68.1.29/30
  ipv6 address 2001:db8:1:29::1/64
!