!
! FRR Configuration for r-as200 (AS200 - transit, không cần sửa)
!
hostname r-as200
password zebra
enable password zebra
!
! Interface toward r-as100
interface eth1
  ip address 100.64.12.2/30
!
! Interface toward r-as300
interface eth2
  ip address 100.64.23.1/30
!
line vty
!
router bgp 200
  bgp router-id 100.64.12.2
  no bgp ebgp-requires-policy
  neighbor 100.64.12.1 remote-as 100
  neighbor 100.64.23.2 remote-as 300
!
